//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class inspectorsDBcopyEntities3 : DbContext
    {
        public inspectorsDBcopyEntities3()
            : base("name=inspectorsDBcopyEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<agencyTbl> agencyTbls { get; set; }
        public virtual DbSet<calendarTbl> calendarTbls { get; set; }
        public virtual DbSet<cityTbl> cityTbls { get; set; }
        public virtual DbSet<inspectorTbl> inspectorTbls { get; set; }
        public virtual DbSet<routsTbl> routsTbls { get; set; }
        public virtual DbSet<schedulingTbl> schedulingTbls { get; set; }
        public virtual DbSet<stop_timesTbl> stop_timesTbl { get; set; }
        public virtual DbSet<stopsTbl> stopsTbls { get; set; }
        public virtual DbSet<tripsTbl> tripsTbls { get; set; }
        public virtual DbSet<workHour> workHours { get; set; }
    
        [DbFunction("inspectorsDBcopyEntities3", "GetStopTimesForDict1")]
        public virtual IQueryable<GetStopTimesForDict1_Result> GetStopTimesForDict1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetStopTimesForDict1_Result>("[inspectorsDBcopyEntities3].[GetStopTimesForDict1]()");
        }
    
        [DbFunction("inspectorsDBcopyEntities3", "GetTripsForDictInit")]
        public virtual IQueryable<GetTripsForDictInit_Result> GetTripsForDictInit()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetTripsForDictInit_Result>("[inspectorsDBcopyEntities3].[GetTripsForDictInit]()");
        }
    }
}
