//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class schedulingTbl
    {
        public int scheduling_id { get; set; }
        public Nullable<int> inspector_id { get; set; }
        public Nullable<int> route_id { get; set; }
        public string trip_id { get; set; }
        public int stop_id { get; set; }
        public System.TimeSpan arrival_time { get; set; }
        public Nullable<System.DateTime> dateToday { get; set; }
        public Nullable<int> workhour_id { get; set; }
    
        public virtual inspectorTbl inspectorTbl { get; set; }
        public virtual routsTbl routsTbl { get; set; }
        public virtual stopsTbl stopsTbl { get; set; }
        public virtual workHour workHour { get; set; }
    }
}
