//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tripsTbl
    {
        public int route_id { get; set; }
        public int service_id { get; set; }
        public string trip_id { get; set; }
        public string trip_headsign { get; set; }
        public int direction_id { get; set; }
        public Nullable<double> shape_id { get; set; }
        public Nullable<System.DateTime> last_date { get; set; }
        public Nullable<System.TimeSpan> last_time { get; set; }
        public int id { get; set; }
        public Nullable<System.DateTime> before_last_date { get; set; }
        public Nullable<System.TimeSpan> before_last_time { get; set; }
        public Nullable<int> num_stops { get; set; }
    
        public virtual calendarTbl calendarTbl { get; set; }
        public virtual routsTbl routsTbl { get; set; }
    }
}
